event_date;even_class;event_desc;event_file;event_line;file_or_reason
2019-04-17 14:38:45.568598;ValueError;could not convert string to float: 'd';test.py;5;POSTPAGO
2019-04-17 14:39:01.481138;ValueError;could not convert string to float: 'c';test.py;5;POSTPAGO
2019-04-16 14:39:01.481138;ValueError;could not convert string to float: 'c';test.py;5;POSTPAGO
2019-04-16 14:39:01.481138;ValueError;could not convert string to float: 'c';test.py;5;POSTPAGO
2019-04-16 14:39:01.481138;ValueError;could not convert string to float: 'c';test.py;5;POSTPAGO
2019-04-15 14:39:01.481138;ValueError;could not convert string to float: 'c';test.py;5;POSTPAGO
2019-04-15 14:39:01.481138;ValueError;could not convert string to float: 'c';test.py;5;POSTPAGOS
2019-04-22 08:00:40.595037;pyodbc.DataError;('22007', '[22007] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)');deletedatabase.py;28;agent
2019-04-22 08:01:58.908947;pyodbc.DataError;('22007', '[22007] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)');deletedatabase.py;28;agent
2019-04-22 08:02:18.884845;pyodbc.DataError;('22007', '[22007] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)');deletedatabase.py;28;agent
2019-04-22 08:02:19.694065;pyodbc.DataError;('22007', '[22007] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)');deletedatabase.py;28;agent
2019-04-22 08:02:32.673190;pyodbc.DataError;('22007', '[22007] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string. (241) (SQLExecDirectW)');deletedatabase.py;28;agent
2019-04-23 17:02:30.306227;UnicodeDecodeError;'utf-8' codec can't decode byte 0xd1 in position 17: invalid continuation byte;validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:12:41.346564;AttributeError;'Series' object has no attribute 'set';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:13:15.631930;AttributeError;'Series' object has no attribute 'set';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:26:28.502652;AttributeError;'NoneType' object has no attribute 'format';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:27:33.488711;AttributeError;'NoneType' object has no attribute 'format';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:30:22.708212;smtplib.SMTPAuthenticationError;(535, b'5.7.8 Error: authentication failed: authentication failure');emailsetting.py;81;QUITO GONZALES, ERNESTO EDGAR
2019-04-23 17:36:37.573872;FileNotFoundError;[WinError 3] El sistema no puede encontrar la ruta especificada: '\\logs\\info_event_log.csv';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:38:51.469890;NotADirectoryError;[WinError 267] El nombre del directorio no es válido: 'logs\\info_event_log.csv';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:39:55.598919;NotADirectoryError;[WinError 267] El nombre del directorio no es válido: 'C:\\Users\\equito\\Documents\\Proyectos Python\\Entel Chile\\logs\\info_event_log.csv';validationfiles.py;65;TRAFICO 20190422.html
2019-04-23 17:42:43.880990;AttributeError;'NoneType' object has no attribute 'split';validationfiles.py;65;TRAFICO 20190422.html
2019-04-24 09:58:59.584112;TypeError;descriptor 'strftime' requires a 'datetime.date' object but received a 'numpy.ndarray';validationfiles.py;39;TRAFICO 20190422.html
2019-04-24 09:59:33.750675;TypeError;descriptor 'strftime' requires a 'datetime.date' object but received a 'numpy.ndarray';validationfiles.py;39;TRAFICO 20190423.html
2019-04-24 17:06:22.085724;AttributeError;'NoneType' object has no attribute 'format';validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 17:07:38.833150;AttributeError;'NoneType' object has no attribute 'format';validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 17:08:32.840419;AttributeError;'NoneType' object has no attribute 'format';validationfiles.py;46;TIEMPO 20190407.html
2019-04-24 17:10:17.734292;AttributeError;'NoneType' object has no attribute 'format';validationfiles.py;45;TIEMPO 20190407.html
2019-04-24 17:12:22.504497;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;43;TIEMPO 20190407.html
2019-04-24 17:14:11.873572;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;42;TIEMPO 20190407.html
2019-04-24 17:17:05.091361;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;45;TIEMPO 20190407.html
2019-04-24 21:36:10.344058;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 21:40:12.447776;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 21:43:27.617294;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 21:51:14.896049;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 21:53:26.434339;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 21:55:50.078465;IndexError;index 0 is out of bounds for axis 0 with size 0;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 21:58:14.507654;ValueError;cannot index with vector containing NA / NaN values;validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 22:02:56.544831;AttributeError;'float' object has no attribute 'split';validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 22:04:19.004267;AttributeError;'float' object has no attribute 'split';validationfiles.py;44;TIEMPO 20190407.html
2019-04-24 22:06:03.982123;AttributeError;'float' object has no attribute 'split';validationfiles.py;44;TIEMPO 20190407.html
2019-04-25 09:09:42.344030;sqlalchemy.exc.ProgrammingError;"(pyodbc.ProgrammingError) ('42S22', ""[42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'DetallePrLogin'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'DetalleTMO'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosAbandonedRinging'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosInbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosLlamadosMenos10segTMO'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosOutbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoPromedioInbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoPromedioOutbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoACW'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoHold'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoInbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoLogin'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoNotReady'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoOutbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoReady'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiemposNotReadyTiempoNotReady'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)"")
[SQL: INSERT INTO [Base_In].trafico (object, [Fecha], [DetallePrLogin], [DetalleTMO], [LlamadosAbandonedRinging], [LlamadosInbound], [LlamadosLlamadosMenos10segTMO], [LlamadosOutbound], [TiempoPromedioInbound], [TiempoPromedioOutbound], [TiempoACW], [TiempoHold], [TiempoInbound], [TiempoLogin], [TiempoNotReady], [TiempoOutbound], [TiempoReady], [TiemposNotReadyTiempoNotReady], [FileName], [LoadDate]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 1, 0), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 13, 0), '35.52', '204.45', '0', '36', '4', '4', 123, 227, 0, 0, 6773, 10535, 350, 1405, 3300, 350, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 1, 15), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 13, 15), '39.52', '149.53', '0', '45', '4', '4', 80, 101, 0, 178, 6723, 9427, 902, 426, 3773, 902, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 1, 30), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 13, 30), '23.99', '101.79', '0', '38', '0', '0', 104, 895, 0, 0, 3868, 9673, 1006, 0, 2321, 1006, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 1, 45), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 13, 45), '22.35', '133.88', '0', '38', '1', '3', 118, 90, 0, 542, 3764, 9598, 405, 1183, 2600, 405, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833))  ... displaying 10 of 50 total bound parameter sets ...  ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 7, 0), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 23, 19, 0), '30.07', '173.36', '0', '22', '0', '0', 123, 0, 0, 205, 3609, 7200, 148, 0, 2877, 148, 'TIEMPO 20190423.html', datetime.datetime(2019, 4, 25, 9, 9, 7, 850833)))]
(Background on this error at: http://sqlalche.me/e/f405)";insertdatabase.py;15;trafico
2019-04-25 09:10:26.245371;sqlalchemy.exc.ProgrammingError;"(pyodbc.ProgrammingError) ('42S22', ""[42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'DetallePrLogin'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'DetalleTMO'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosAbandonedRinging'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosInbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosLlamadosMenos10segTMO'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'LlamadosOutbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoPromedioInbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoPromedioOutbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoACW'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoHold'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoInbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoLogin'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoNotReady'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoOutbound'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiempoReady'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid column name 'TiemposNotReadyTiempoNotReady'. (207); [42S22] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)"")
[SQL: INSERT INTO [Base_In].trafico (object, [Fecha], [DetallePrLogin], [DetalleTMO], [LlamadosAbandonedRinging], [LlamadosInbound], [LlamadosLlamadosMenos10segTMO], [LlamadosOutbound], [TiempoPromedioInbound], [TiempoPromedioOutbound], [TiempoACW], [TiempoHold], [TiempoInbound], [TiempoLogin], [TiempoNotReady], [TiempoOutbound], [TiempoReady], [TiemposNotReadyTiempoNotReady], [FileName], [LoadDate]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 1, 0), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 13, 0), '16.16', '115.63', '0', '37', '4', '1', 85, 68, 0, 843, 3483, 12600, 901, 68, 6566, 901, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 1, 15), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 13, 15), '12.60', '112.32', '0', '26', '3', '2', 109, 130, 0, 192, 2692, 11989, 0, 261, 7961, 0, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 1, 30), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 13, 30), '16.54', '109.40', '0', '36', '3', '4', 111, 25, 0, 174, 4100, 13424, 324, 102, 7933, 324, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 1, 45), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 13, 45), '22.71', '117.24', '0', '46', '6', '0', 80, 0, 0, 0, 5393, 14247, 323, 0, 9783, 323, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624))  ... displaying 10 of 50 total bound parameter sets ...  ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 7, 0), '0.00', '0.00', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)), ('ALLUS_APPENTEL', datetime.datetime(2019, 4, 24, 19, 0), '33.86', '146.79', '0', '24', '0', '0', 140, 0, 0, 0, 3523, 6243, 811, 0, 1706, 811, 'TIEMPO 20190424.html', datetime.datetime(2019, 4, 25, 9, 9, 55, 439624)))]
(Background on this error at: http://sqlalche.me/e/f405)";insertdatabase.py;15;trafico
2019-05-29 09:33:23.835378;AttributeError;'float' object has no attribute 'replace';getdatasources.py;68;TRAFICO 20190503.html
2019-05-29 09:35:45.477043;AttributeError;'float' object has no attribute 'replace';getdatasources.py;72;TRAFICO 20190503.html
2019-05-29 09:36:59.061373;AttributeError;'float' object has no attribute 'replace';getdatasources.py;78;TRAFICO 20190503.html
2019-05-29 09:38:39.241165;sqlalchemy.exc.DataError;"(pyodbc.DataError) ('22018', ""[22018] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '1.0' to data type int. (245) (SQLExecDirectW)"")
[SQL: INSERT INTO [Base_In].trafico (object, [Fecha], [Abandonadas], [Abandonadas010], [Abandonadas015], [Abandonadas020], [Abandonadas05], [Contestadas], [Contestadas010], [Contestadas015], [Contestadas020], [Contestadas05], [Distribuidas], [Entrantes], [NA], [NS_05S], [NS_10S], [NS_15S], [NS_20S], [FileName], [LoadDate]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 0), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 0), '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', 100.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 15), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 15), '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '2.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 30), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 30), '2.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '2.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 45), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 45), '1.0', '0.0', '0.0', '0.0', '0.0', '3.0', '0.0', '0.0', '0.0', '0.0', '3.0', '7.0', 42.86, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334))  ... displaying 10 of 50 total bound parameter sets ...  ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 7, 0), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 19, 0), '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 9, 38, 36, 811334)))]
(Background on this error at: http://sqlalche.me/e/9h9h)";insertdatabase.py;19;trafico
2019-05-29 09:45:00.347086;TypeError;read_html() got an unexpected keyword argument 'dtype';getdatasources.py;34;TRAFICO 20190503.html
2019-05-29 09:45:55.436006;TypeError;data type not understood;getdatasources.py;51;TRAFICO 20190503.html
2019-05-29 09:46:40.123126;AttributeError;'float' object has no attribute 'replace';getdatasources.py;67;TRAFICO 20190503.html
2019-05-29 09:52:28.954500;AttributeError;'float' object has no attribute 'replace';getdatasources.py;67;TRAFICO 20190503.html
2019-05-29 09:53:33.279243;AttributeError;'float' object has no attribute 'replace';getdatasources.py;72;TRAFICO 20190503.html
2019-05-29 09:56:55.536971;ModuleNotFoundError;No module named 'xlwt';getdatasources.py;87;TRAFICO 20190503.html
2019-05-29 10:02:59.419222;TypeError;data type not understood;getdatasources.py;51;TRAFICO 20190503.html
2019-05-29 10:04:22.205149;TypeError;data type not understood;getdatasources.py;51;TRAFICO 20190503.html
2019-05-29 10:05:12.869020;TypeError;data type not understood;getdatasources.py;51;TRAFICO 20190503.html
2019-05-29 10:06:18.445103;ValueError;invalid literal for int() with base 10: '1.0';getdatasources.py;67;TRAFICO 20190503.html
2019-05-29 10:07:25.191815;TypeError;replace() argument 2 must be str, not int;getdatasources.py;67;TRAFICO 20190503.html
2019-05-29 10:16:49.480074;AttributeError;'float' object has no attribute 'replace';getdatasources.py;68;TRAFICO 20190503.html
2019-05-29 10:22:04.981650;sqlalchemy.exc.DataError;"(pyodbc.DataError) ('22018', ""[22018] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '1.0' to data type int. (245) (SQLExecDirectW)"")
[SQL: INSERT INTO [Base_In].trafico (object, [Fecha], [Abandonadas], [Abandonadas010], [Abandonadas015], [Abandonadas020], [Abandonadas05], [Contestadas], [Contestadas010], [Contestadas015], [Contestadas020], [Contestadas05], [Distribuidas], [Entrantes], [NA], [NS_05S], [NS_10S], [NS_15S], [NS_20S], [FileName], [LoadDate]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 0), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 0), '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', 100.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 15), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 15), '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '2.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 30), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 30), '2.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '2.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 45), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 45), '1.0', '0.0', '0.0', '0.0', '0.0', '3.0', '0.0', '0.0', '0.0', '0.0', '3.0', '7.0', 42.86, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860))  ... displaying 10 of 50 total bound parameter sets ...  ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 7, 0), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 19, 0), '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 22, 0, 713860)))]
(Background on this error at: http://sqlalche.me/e/9h9h)";insertdatabase.py;19;trafico
2019-05-29 10:37:28.074656;sqlalchemy.exc.DataError;"(pyodbc.DataError) ('22018', ""[22018] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Conversion failed when converting the nvarchar value '1.0' to data type int. (245) (SQLExecDirectW)"")
[SQL: INSERT INTO [Base_In].trafico (object, [Fecha], [Abandonadas], [Abandonadas010], [Abandonadas015], [Abandonadas020], [Abandonadas05], [Contestadas], [Contestadas010], [Contestadas015], [Contestadas020], [Contestadas05], [Distribuidas], [Entrantes], [NA], [NS_05S], [NS_10S], [NS_15S], [NS_20S], [FileName], [LoadDate]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 0), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 0), '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', 100.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 15), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 15), '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '2.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 30), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 30), '2.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '2.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 1, 45), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 13, 45), '1.0', '0.0', '0.0', '0.0', '0.0', '3.0', '0.0', '0.0', '0.0', '0.0', '3.0', '7.0', 42.86, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627))  ... displaying 10 of 50 total bound parameter sets ...  ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 7, 0), '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)), ('8101-ALLUS_SK1094', datetime.datetime(2019, 5, 3, 19, 0), '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', 0.0, 0.0, 0.0, 0.0, 0.0, 'TRAFICO 20190503.html', datetime.datetime(2019, 5, 29, 10, 37, 26, 594627)))]
(Background on this error at: http://sqlalche.me/e/9h9h)";insertdatabase.py;19;trafico
2019-05-29 11:02:15.267488;ValueError;invalid literal for int() with base 10: '1.0';getdatasources.py;67;TRAFICO 20190503.html
2019-06-19 11:11:05.182697;xlrd.biffh.XLRDError;No sheet named '';readfiles.py;12;C:\Users\equito\Documents\Proyectos Python\Beta 1.0\setting.xlsx
2019-06-19 11:11:23.477348;xlrd.biffh.XLRDError;No sheet named '0';readfiles.py;12;C:\Users\equito\Documents\Proyectos Python\Beta 1.0\setting.xlsx
